### PR TITLE
Fix #279

### LINKED ISSUE #279: [Bug]: Redstone torch will become extinguished torch in the space
### Bug Description

When I place the torch without air pressure, it will become extinguished torch after a while

### How to Reproduce?

1. Create a space station
2. Place a redstone torch
3. Wait for a while (probably you need use it? I'm not really sure)
4. The redstone torch will become extinguished torch

### Expected Behavior

The redstone torch will keep it self, never be extinguished

### Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge / Spigot hybrid jar

### Logs or additional context

_No response_

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

### PR DESCRIPTION
**Pull request by gisellevonbingen**
Gif

Referencing.
https://github.com/terrarium-earth/Ad-Astra/blob/1edc6ffce34cb4e6d9953b3f16a4205723382fd0/common/src/main/java/earth/terrarium/ad_astra/mixin/oxygen/BlockItemMixin.java#L58-L64

### CODE REVIEW

File: common/src/main/java/earth/terrarium/ad_astra/common/util/OxygenUtils.java [hunk 1]
```diff
@@ -136,8 +136,10 @@ public static void deoxygenizeBlocks(ServerLevel level, Set<BlockPos> entries, B
                 }
 
                 if (block instanceof TorchBlock && !block.equals(Blocks.SOUL_TORCH) && !block.equals(Blocks.SOUL_WALL_TORCH)) {
-                    level.setBlockAndUpdate(pos, ModBlocks.EXTINGUISHED_TORCH.get().defaultBlockState());
-                    continue;
+                    if (!block.equals(Blocks.REDSTONE_TORCH) && !block.equals(Blocks.REDSTONE_WALL_TORCH)) {
```
Comment (ThatGravyBoat) [inline common/src/main/java/earth/terrarium/ad_astra/common/util/OxygenUtils.java:139]: This should  likely be changed to a tag check as to make better compatibility with other mods

**Review by ThatGravyBoat — CHANGES_REQUESTED** [review]

File: common/src/main/java/earth/terrarium/ad_astra/common/util/OxygenUtils.java (hunk 1 above)
Comment (gisellevonbingen) [reply common/src/main/java/earth/terrarium/ad_astra/common/util/OxygenUtils.java:139]: I referenced from another code from Ad Astra.
https://github.com/terrarium-earth/Ad-Astra/blob/1edc6ffce34cb4e6d9953b3f16a4205723382fd0/common/src/main/java/earth/terrarium/ad_astra/mixin/oxygen/BlockItemMixin.java#L58-L64

If should be change condition of checking , I think it's appropriate to create new issue for only about change check.

Comment (gisellevonbingen) [reply common/src/main/java/earth/terrarium/ad_astra/common/util/OxygenUtils.java:139]: Then to make it perfect, i think it would be a good idea to add a deoxygenation recipe type.
Since we don't know exactly what the items added in other mods are made of,
It should be specified in the recipe json.

Comment (ThatGravyBoat) [reply common/src/main/java/earth/terrarium/ad_astra/common/util/OxygenUtils.java:139]: Ok yeah  a recipe json would be best as for now ill approve this so it doesn't break redstone torches in the mean time.

**Review by ThatGravyBoat — APPROVED** [review]

**Review by AlexNijjar — APPROVED** [review]

**Comment by AlexNijjar** [comment]
These PRs target the 1.19 branch; however that version is no longer supported. If possible, can you change the PR to target the 1.20.x branch?

**Comment by gisellevonbingen** [comment]
But reporting man is playing in 1.19.2.

**Comment by AlexNijjar** [comment]
I know. But 1.19.2 might not be updated again. I'm fine merging this, it'll just need to be merged into 1.20.x as well.
